ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS event_type VARCHAR(10) DEFAULT 'pageview';
ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS lat REAL DEFAULT 0;
ALTER TABLE raw_events ADD COLUMN IF NOT EXISTS lon REAL DEFAULT 0;
ALTER TABLE raw_events ALTER COLUMN api_key SET DEFAULT '';
ALTER TABLE raw_events ALTER COLUMN api_key DROP NOT NULL;
ALTER TABLE active_sessions ADD COLUMN IF NOT EXISTS city VARCHAR(100) DEFAULT '';
ALTER TABLE active_sessions ADD COLUMN IF NOT EXISTS lat REAL DEFAULT 0;
ALTER TABLE active_sessions ADD COLUMN IF NOT EXISTS lon REAL DEFAULT 0;